/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as MyRouteImport } from './routes/my'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StationIdIndexRouteImport } from './routes/station/$id/index'
import { Route as StationIdPostsIndexRouteImport } from './routes/station/$id/posts/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationIdIndexRoute = StationIdIndexRouteImport.update({
  id: '/station/$id/',
  path: '/station/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationIdPostsIndexRoute = StationIdPostsIndexRouteImport.update({
  id: '/station/$id/posts/',
  path: '/station/$id/posts/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRoute
  '/ranking': typeof RankingRoute
  '/signup': typeof SignupRoute
  '/station/$id': typeof StationIdIndexRoute
  '/station/$id/posts': typeof StationIdPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRoute
  '/ranking': typeof RankingRoute
  '/signup': typeof SignupRoute
  '/station/$id': typeof StationIdIndexRoute
  '/station/$id/posts': typeof StationIdPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRoute
  '/ranking': typeof RankingRoute
  '/signup': typeof SignupRoute
  '/station/$id/': typeof StationIdIndexRoute
  '/station/$id/posts/': typeof StationIdPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/my'
    | '/ranking'
    | '/signup'
    | '/station/$id'
    | '/station/$id/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/my'
    | '/ranking'
    | '/signup'
    | '/station/$id'
    | '/station/$id/posts'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/my'
    | '/ranking'
    | '/signup'
    | '/station/$id/'
    | '/station/$id/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MyRoute: typeof MyRoute
  RankingRoute: typeof RankingRoute
  SignupRoute: typeof SignupRoute
  StationIdIndexRoute: typeof StationIdIndexRoute
  StationIdPostsIndexRoute: typeof StationIdPostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station/$id/': {
      id: '/station/$id/'
      path: '/station/$id'
      fullPath: '/station/$id'
      preLoaderRoute: typeof StationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station/$id/posts/': {
      id: '/station/$id/posts/'
      path: '/station/$id/posts'
      fullPath: '/station/$id/posts'
      preLoaderRoute: typeof StationIdPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MyRoute: MyRoute,
  RankingRoute: RankingRoute,
  SignupRoute: SignupRoute,
  StationIdIndexRoute: StationIdIndexRoute,
  StationIdPostsIndexRoute: StationIdPostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
